
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

from PIL import ImageTk
from sympy.core.random import random

from generation_type import GenerationType
from model_handler import ModelHandler
from observer import Observer


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)



window = Tk()

window.geometry("1920x1080")
window.configure(bg = "#FFFFFF")


window.resizable(False, False)
window.mainloop()

class TextModule(Observer):
    prompt = None
    output = None
    output_label_global = None
    prompt_label_global = None
    user_input_global = None
    model_handler = None
    model_label = None
    parameters = None
    parameters_entry_list = None
    image_label = None
    generation_type = GenerationType.TEXT
    gen_type_label = None
    processing_type_button = None
    image_cache = None # stored image if the user want to save it

    def __init__(self,window):
        self.prompt = "I like trains"
        self.output = "I hate trains"
        self.output_label_global = None
        self.prompt_label_global = None
        self.user_input_global = None
        self.parameters = {}
        self.model_handler = ModelHandler()
        self.model_handler.add_observer(self)


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1080,
    width = 1920,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1920.0,
    1080.0,
    fill="#D9D9D9",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    960.0,
    540.0,
    image=image_image_1
)

canvas.create_rectangle(
    68.0,
    90.0,
    452.0,
    214.0,
    fill="#6C33F1",
    outline="")

canvas.create_rectangle(
    23.0,
    28.0,
    506.0,
    152.0,
    fill="#1A0350",
    outline="")

canvas.create_text(
    115.0,
    49.0,
    anchor="nw",
    text="ŒSTRO-GEN",
    fill="#FFFFFF",
    font=("Khmer", 48 * -1)
)

canvas.create_text(
    87.0,
    152.0,
    anchor="nw",
    text="Project : ",
    fill="#FFFFFF",
    font=("Khmer", 32 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    960.0,
    118.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=772.0,
    y=89.0,
    width=376.0,
    height=56.0
)

canvas.create_text(
    924.0,
    64.0,
    anchor="nw",
    text="Prompt",
    fill="#FFFFFF",
    font=("Khmer", 20 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: Button(input_frame, text="CURRENTLY : CPU MODE", command=lambda: self.change_processing_type()),
    relief="flat"
)

button_1.place(
    x=843.0,
    y=0.0,
    width=211.0,
    height=34.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=148.0,
    y=807.0,
    width=211.0,
    height=34.0
)

canvas.create_rectangle(
    101.0,
    304.0,
    408.0,
    807.0,
    fill="#330B0B",
    outline="")

canvas.create_rectangle(
    135.0,
    362.0,
    372.0,
    749.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    190.0,
    307.0,
    anchor="nw",
    text="Models :",
    fill="#FFFFFF",
    font=("Khmer", 32 * -1)
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=168.0,
    y=757.0,
    width=172.0,
    height=34.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=863.0,
    y=168.0,
    width=194.0,
    height=41.0
)



