
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Haken\Downloads\Tkinter-Designer-master\Tkinter-Designer-master\Dossier3\build\assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("211x34")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 34,
    width = 211,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    105.0,
    17.0,
    image=image_image_1
)

canvas.create_rectangle(
    0.0,
    0.0,
    211.0,
    31.0,
    fill="#682121",
    outline="")

canvas.create_text(
    48.0,
    0.0,
    anchor="nw",
    text="GPU Version",
    fill="#FFFFFF",
    font=("Khmer", 20 * -1)
)
window.resizable(False, False)
window.mainloop()
