build:
    pyinstaller:
        args:
            - --collect-data=sv_ttk
description: Prototype Visual-Novel builder powered by AI.
models:
    - name: microsoft/phi-2
      path: models/microsoft/phi-2/model
      module: transformers
      class: PhiForCausalLM
      options: {}
      tokenizers:
        - path: models/microsoft/phi-2/AutoTokenizer
          class: AutoTokenizer
          options: {}
      pipelinetag: text-generation
      source: hugging_face
      addtobinaryfile: true
      isdownloaded: true
      version: "2024-02-06T12:36:24.000Z"
      accesstoken: ""
    - name: openai-community/openai-gpt
      path: models/openai-community/openai-gpt/model
      module: transformers
      class: OpenAIGPTLMHeadModel
      options: {}
      tokenizers:
        - path: models/openai-community/openai-gpt/AutoTokenizer
          class: AutoTokenizer
          options: {}
      pipelinetag: text-generation
      source: hugging_face
      addtobinaryfile: true
      isdownloaded: true
      version: ""
      accesstoken: ""
    - name: CompVis/stable-diffusion-v1-4
      path: models/CompVis/stable-diffusion-v1-4
      module: diffusers
      class: StableDiffusionPipeline
      options: {}
      tokenizers: []
      pipelinetag: text-to-image
      source: hugging_face
      addtobinaryfile: true
      isdownloaded: true
      version: ""
      accesstoken: ""
name: Œstro-gen
sdk-tag: v1.1.3
update-suggested: true
version: 1.0.0
